import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

type TranslationMap = Record<string, string>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, ...args: Array<string | number>) => string;
}

const translations: Record<Language, TranslationMap> = {
  zh: {
    app_title: 'DLUT-GPA',
    app_desc: 'DLUT-GPA',
    sandbox_mode: '沙盒模式',
    confirm_reset: '确定要重置所有数据吗？此操作不可撤销。',
    reset: '重置',
    data_mgmt: '数据管理',
    share: '分享报告',
    enter_sandbox: '进入沙盒',
    sandbox_active: '沙盒模式已激活',
    total_gpa: '总 GPA',
    based_on_credits: '基于 {0} 学分',
    compulsory_gpa: '必修 GPA',
    compulsory_desc: '必修 {0} 学分',
    avg_score: '加权平均分',
    hundred_scale: '百分制',
    course_count: '课程数量',
    selected_total: '已选 {0} 门课程',
    all_semesters: '全部学期',
    selected_semesters: '已选 {0} 个学期',
    filter_semester: '筛选学期',
    all_types: '全部类型',
    type_compulsory: '必修',
    type_elective: '选修',
    type_optional: '任选',
    filter_type: '筛选类型',
    core_only: '仅核心课',
    search_placeholder: '搜索课程名称...',
    score_dist: '成绩分布',
    histogram: '直方图',
    ocr_import_title: 'OCR 成绩导入',
    ocr_upload_prompt: '点击上传教务系统截图',
    ocr_supported_formats: '支持 JPG、PNG、WEBP 格式',
    upload_image: '上传图片',
    ocr_scanning: '正在扫描',
    ocr_no_courses_found: '未在图片中找到课程信息，请检查截图是否包含成绩单',
    ocr_error_occurred: 'OCR 识别过程中发生错误，请稍后重试',
    ocr_instruction_line1: '1. 截取包含课程信息的教务系统页面',
    ocr_instruction_line2: '2. 确保截图包含课程名称、学分和成绩',
    simulation_mode_title: 'GPA 模拟器',
    original_gpa: '原始 GPA',
    simulated_gpa: '模拟 GPA',
    credits: '学分',
    current_score: '当前分数',
    simulation_instructions: '拖动滑块调整模拟分数，实时查看 GPA 变化',
    show_simulation: '显示模拟器',
    hide_simulation: '隐藏模拟器',
    show_radar: '显示雷达图',
    hide_radar: '隐藏雷达图',
    academic_radar_title: '学业雷达图',
    theme_light: '浅色主题',
    theme_dark: '深色主题',
    category_math: '数学类',
    category_english: '英语类',
    category_major: '专业核心',
    category_general: '通识教育',
    category_sports: '体育类',
    category_other: '其他',
    scores: '分数',
    no_data_for_radar: '暂无数据绘制雷达图',
    no_data: '暂无数据',
    app_calc_title: '留学申请计算器',
    sandbox_banner: '您正在沙盒模式中，所有更改都不会保存到本地存储，除非您选择保存退出。',
    exit_sandbox_discard: '放弃更改退出',
    exit_sandbox_save: '保存更改退出',
    nav_overview: '总览',
    nav_courses: '课程',
    nav_analysis: '分析',
    analysis_overview: '总览分析',
    analysis_simulation: '成绩仿真',
    analysis_radar: '学业雷达',
    analysis_advisor: '智能建议',
    overview_title: '学业控制台',
    overview_primary_cta: '进入课程',
    overview_secondary_cta: '查看分析',
    overview_state_live: '本地自动保存',
    overview_state_sandbox: '沙盒演算中',
    overview_terms: '已覆盖学期',
    overview_active: '计入课程',
    section_method: '计算方式',
    section_status: '当前状态',
    quick_metrics: '核心指标',
    course_workspace_title: '课程控制台',
    course_workspace_desc: '录入、筛选和档案表在同一工作区。',
    new_course: '新建课程',
    close_entry: '关闭录入',
    course_entry: '课程录入',
    course_entry_desc: '输入课程信息后立即重算 GPA。',
    analysis_title: '分析中心',
    analysis_desc: '切换总览、仿真、雷达和建议。',
    filter_state_filtered: '筛选中',
    filter_state_all: '全部课程',
    clear_filters: '清除筛选',
    empty_courses_title: '暂无课程',
    empty_courses_desc: '添加第一门课程或导入现有成绩单。',
    empty_filtered_courses_title: '暂无匹配课程',
    empty_filtered_courses_desc: '当前筛选条件下没有课程，尝试清除筛选或切换其他条件。',
    import_courses: '导入数据',
    close_panel: '关闭面板',
    language_toggle: '切换语言',
    chart_loading: '模块加载中...',
    theme_light_short: '亮',
    theme_dark_short: '暗'
  },
  en: {
    app_title: 'DLUT-GPA',
    app_desc: 'DLUT-GPA',
    sandbox_mode: 'Sandbox Mode',
    confirm_reset: 'Are you sure you want to reset all data? This action cannot be undone.',
    reset: 'Reset',
    data_mgmt: 'Data Mgmt',
    share: 'Share Report',
    enter_sandbox: 'Enter Sandbox',
    sandbox_active: 'Sandbox Active',
    total_gpa: 'Total GPA',
    based_on_credits: 'Based on {0} credits',
    compulsory_gpa: 'Compulsory GPA',
    compulsory_desc: 'Compulsory {0} credits',
    avg_score: 'Weighted Avg',
    hundred_scale: '100 Scale',
    course_count: 'Courses',
    selected_total: 'Selected {0} courses',
    all_semesters: 'All Semesters',
    selected_semesters: 'Selected {0} semesters',
    filter_semester: 'Filter Semester',
    all_types: 'All Types',
    type_compulsory: 'Compulsory',
    type_elective: 'Elective',
    type_optional: 'Optional',
    filter_type: 'Filter Type',
    core_only: 'Core Only',
    search_placeholder: 'Search course name...',
    score_dist: 'Score Dist',
    histogram: 'Histogram',
    ocr_import_title: 'OCR Import',
    ocr_upload_prompt: 'Click to upload academic record screenshot',
    ocr_supported_formats: 'Supports JPG, PNG, WEBP formats',
    upload_image: 'Upload Image',
    ocr_scanning: 'Scanning',
    ocr_no_courses_found: 'No course information found in the image, please check if the screenshot contains transcript',
    ocr_error_occurred: 'An error occurred during OCR recognition, please try again later',
    ocr_instruction_line1: '1. Screenshot the academic record page from academic system',
    ocr_instruction_line2: '2. Ensure the screenshot includes course name, credits, and grades',
    simulation_mode_title: 'GPA Simulator',
    original_gpa: 'Original GPA',
    simulated_gpa: 'Simulated GPA',
    credits: 'Credits',
    current_score: 'Current Score',
    simulation_instructions: 'Drag sliders to adjust simulated scores and see real-time GPA changes',
    show_simulation: 'Show Simulator',
    hide_simulation: 'Hide Simulator',
    show_radar: 'Show Radar',
    hide_radar: 'Hide Radar',
    academic_radar_title: 'Academic Radar',
    theme_light: 'Light Theme',
    theme_dark: 'Dark Theme',
    category_math: 'Math',
    category_english: 'English',
    category_major: 'Major Core',
    category_general: 'General Ed',
    category_sports: 'Sports',
    category_other: 'Other',
    scores: 'Scores',
    no_data_for_radar: 'No data to draw radar chart',
    no_data: 'No Data',
    app_calc_title: 'Application Calculator',
    sandbox_banner: 'You are in Sandbox Mode. Changes will not be saved to local storage unless you choose to save and exit.',
    exit_sandbox_discard: 'Discard and Exit',
    exit_sandbox_save: 'Save and Exit',
    nav_overview: 'Overview',
    nav_courses: 'Courses',
    nav_analysis: 'Analysis',
    analysis_overview: 'Analysis Overview',
    analysis_simulation: 'Simulation',
    analysis_radar: 'Radar',
    analysis_advisor: 'Advisor',
    overview_title: 'Academic Control Center',
    overview_primary_cta: 'Open Courses',
    overview_secondary_cta: 'Open Analysis',
    overview_state_live: 'Local autosave',
    overview_state_sandbox: 'Sandbox running',
    overview_terms: 'Terms Covered',
    overview_active: 'Active Courses',
    section_method: 'Method',
    section_status: 'Status',
    quick_metrics: 'Core Metrics',
    course_workspace_title: 'Course Console',
    course_workspace_desc: 'Input, filters, and the ledger live in one operational space.',
    new_course: 'New Course',
    close_entry: 'Close Entry',
    course_entry: 'Course Entry',
    course_entry_desc: 'Enter a course and recalculate GPA immediately.',
    analysis_title: 'Analysis Hub',
    analysis_desc: 'Switch between overview, simulation, radar, and advisor.',
    filter_state_filtered: 'Filtered',
    filter_state_all: 'All Courses',
    clear_filters: 'Clear Filters',
    empty_courses_title: 'No Courses Yet',
    empty_courses_desc: 'Add the first course or import an existing record.',
    empty_filtered_courses_title: 'No Matching Courses',
    empty_filtered_courses_desc: 'No courses match the current filters. Clear them or switch to another combination.',
    import_courses: 'Import Data',
    close_panel: 'Close panel',
    language_toggle: 'Switch language',
    chart_loading: 'Loading module...',
    theme_light_short: 'Light',
    theme_dark_short: 'Dark'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, ...args: Array<string | number>) => {
    let translation = translations[language][key] ?? key;

    args.forEach((arg, index) => {
      translation = translation.replace(`{${index}}`, String(arg));
    });

    return translation;
  };

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
